### PR TITLE
Publish open source release policy

### PR DESCRIPTION
**Pull request by SumanthPuram**
**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by jalberto** [comment]
My 2 cents coming from #569 

Software versioning is not just a number or counter, but a sensible way to answer these questions:

- Which version I am using?
  - This is solved with the current proposal, as each docker image will have its own version
  - as the proposed versioning is date-based, and created once per month if there is a hotfix on the very same day, will be confusing. Which one is the hotfix? `18052021.042954` or `18052021.042854`
- Which codebase/commit/tag am I running?
  - This is not solved with the proposal, as there is not a pointer to the code being used in the docker image
  - ideally, this pointer will be a tag in the git repo
  - proposed version format will  work as a tag in git
- Which deps should I use with this version?
  - as rudder-server needs to coordinate with other rudder services like transformers 
  - how I know if `server-18052021.042954` will work with `transformer-10102021.0000`?
  - here is where date-based versioning has issues. is easier to understand SemVer for this, so `server-1.2.9` will work with `transformers-1.2.x`
- it is safe to upgrade or there are breaking changes?
  - here again, date-based has issues, as by date you don't know even if it is a stable version or not
  - SemVer main reason is to solve this, and mostly deps managers will understand it out of the box
- where I check for changes for this version compared with the previous version?
  - so each month I will need to de-compile the docker-image, to know which are the breaking changes?
  - the changleog can use date-based or SemVer as far is clear which changes are in which version

**Comment by SumanthPuram** [comment]
Great, thanks for these details.

To summarise
1. rudder-server and rudder-transformer releases should use sem-ver maintaining compatibility
2. Create tags in GitHub corresponding to releases
3. Add change log as part of Github release

Anything else that you want to suggest?

**Comment by jalberto** [comment]
Great summary @SumanthPuram I tend to over-explain my thoughts :)

I think that will cover all. To clarify I am not suggesting to move from based-date to SemVer, as both can work, but I think is harder with date-based versioning.

Thanks!

**Comment by SumanthPuram** [comment]
Thanks! We will work on this, will keep you posted.

**Comment by jalberto** [comment]
Any progress on this?

**Comment by mderazon** [comment]
@SumanthPuram any way to track breaking changes between releases of Rudderstack ?
For example, changes in transformers like https://github.com/rudderlabs/rudder-transformer/pull/1091 break analytics but I can't find a way to know about these things when upgrading to a new Docker version

**Comment by mderazon** [comment]
https://github.com/rudderlabs/rudder-server/blob/6996d7eeae8f0c85c5c89b51264671e3d6ba68d7/releases.md?plain=1#L3

Is this updated ? I don't see any semver tag in Dockerhub

**Comment by jalberto** [comment]
I really think there is no interest in having a good enough versioning system that allows open-source users to have a more reliable installation

**Pull request closed without merging**
