### PR TITLE
feat: add config param for batch router for name customize

### PR DESCRIPTION
**Pull request by peakle**
# Description

Add feature for batch router via user can add custom prefix for batch.

## Notion Ticket

__

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Comment by maratbakiev2** [comment]
Please, review it and merge. This is very important feature. For example, adding `date=` as a prefix will allow us to declare all folders of rudderstack outputs as a Hive partitioned table

**Comment by gitcommitshow** [comment]
Thank you @peakle for the contribution.

Can you sign [the CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement)?
This is required before we can merge code from a new contributor. [Learn more](https://github.com/rudderlabs/rudder-server/blob/master/CONTRIBUTING.md).

**Comment by peakle** [comment]
> Thank you @peakle for the contribution.
> 
> Can you sign [the CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement)? This is required before we can merge code from a new contributor. [Learn more](https://github.com/rudderlabs/rudder-server/blob/master/CONTRIBUTING.md).

done

**Comment by maratbakiev2** [comment]
@gitcommitshow how we move forward with this? We should wait for review from RS or something else? If we wait for review could you provide approximate deadlines for that?

**Comment by gitcommitshow** [comment]
@maratbakiev2 internal disucssion has been started already. Can't say about the deadline to merge but I'll try to close the discussion before next weekend.

One thing the team pointed out was that the partitioning is already supported for datalake destinations. I don't have complete knowledge about that, let me gather some more info to move the discussion ahead.

**Review by lvrach — APPROVED** [review]

**Review by saurav-malani — APPROVED** [review]

**Comment by maratbakiev2** [comment]
> @maratbakiev2 internal disucssion has been started already. Can't say about the deadline to merge but I'll try to close the discussion before next weekend.
> 
> One thing the team pointed out was that the partitioning is already supported for datalake destinations. I don't have complete knowledge about that, let me gather some more info to move the discussion ahead.

@gitcommitshow 

partitioning in terms of writing to separate folders for each day is indeed supported. But! One of the most popular technologies to process that data is Hive and Hive (Hive Metastore) needs partitions in the format of `column=value`, for example `date=2023-06-08`. While currently rudderstack uses just values  (2023-06-08) as folder names

**Pull request merged**
