### PR TITLE
fix(jobsdb) : clean up getpileupcounts method

### PR DESCRIPTION
**Pull request by cisse21**
## Description of the change

> Get rid of the redundant method `GetPileUpCounts` in `unionQuery.go` and replace the incorrect method in `jobsdb.go` with the correct method.

When the rudder-server starts up , we pre populate the in-memory stats for pileup counts with a db query, we have two different implementations of the same function GetPileUpCounts and with only one of them being the right query , This PR attempts to have a single implementation with the right query

## Notion Link

> [Notion Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=6efe657bfe7a4a2e91a1511a1986787a)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Comment by lvrach** [comment]
@cisse21 Can you provide more details on this changes

**Review by atzoum — APPROVED** [review]
My only comment has to do with the PR's title 🙂. Prefer using lowercase when uppercase is not necessary (eg. method name).

**Comment by cisse21** [comment]
@lvrach  Added more details

**Review by lvrach — APPROVED** [review]

**Comment by lvrach** [comment]
> @lvrach Added more details

Thank you, approved

**Pull request merged**
