### PR TITLE
chore(router): include input payload in inconsistent transformer response error

### PR DESCRIPTION
**Pull request by atzoum**
# Description

Including the payload we send to the transformer for easier debugging

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Comment by lvrach** [comment]
Do we want to merge this in master or use it just for debugging?

**Comment by atzoum** [comment]
> Do we want to merge this in master or use it just for debugging?

I guess for now it would suffice to use it for debugging, but maybe we should deploy a release that contains this log, for future problems. The current PR targets the `release/1.0.x` branch

**Comment by lvrach** [comment]
> we should deploy a release that contains this log

Two problems with printing raw JSON payloads:
1. Things space to multiple lines; breaking parses and tools like loki and grep becomes harder.
2. There is a limit on the line size - each tool has one limit, and it can decide to either omit anything after the limit or push it to the next line.

For the reasons above @fracasula had created a tool that automatically upload big payloads to an s3 storage (with a lot of optimisations not impose performance problems)

**Comment by fracasula** [comment]
> For the reasons above @fracasula had created a tool that automatically upload big payloads to an s3 storage (with a lot of optimisations not impose performance problems)

Another case is that multiple logs can happen at the same time so you could get your JSON output mixed with other entries making it increasingly difficult to get the whole output.

I had implemented a GCP uploader with a leaky bucket approach so that only one upload would take place at a time, any other call to `upload()` would be discarded. It was very useful for sampling/debugging (plus you don't risk as much to incur in big bills or storage limits on GCP due to the leaky bucket approach).

```go
select {
case upload<-file:
    doUpload()
default:
    // discard
}
```

**Pull request closed without merging**
