### PR TITLE
chore: remove readonlyjobsdb and some status handlers

### PR DESCRIPTION
**Pull request by Sidddddarth**
# Description

removing some unused code, functionality.

## Notion Ticket

< Replace with Notion Link >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Comment by atzoum** [comment]
do we need any adaptations in rudder cli as well?

**Comment by Sidddddarth** [comment]
> do we need any adaptations in rudder cli as well?

we do, in progress.

**Review by lvrach — APPROVED** [review]

**Comment by Sidddddarth** [comment]
if we want to discontinue with cli entirely, we could remove [more things](https://github.com/rudderlabs/rudder-server/blob/f328e43a68147c56fe8f446cf9d1e3614be8363b/Dockerfile#L45) as well.
For now I've kept the functionality wrt logging(setting, getting log level).

**Comment by atzoum** [comment]
> if we want to discontinue with cli entirely, we could remove [more things](https://github.com/rudderlabs/rudder-server/blob/f328e43a68147c56fe8f446cf9d1e3614be8363b/Dockerfile#L45) as well. For now I've kept the functionality wrt logging(setting, getting log level).

Is this what we are removing support for?
https://github.com/rudderlabs/rudder-cli/blob/098fa0d59af54ba4ccdc266e5f10100432c326e2/status/status.go#L59

**Comment by Sidddddarth** [comment]
> > if we want to discontinue with cli entirely, we could remove [more things](https://github.com/rudderlabs/rudder-server/blob/f328e43a68147c56fe8f446cf9d1e3614be8363b/Dockerfile#L45) as well. For now I've kept the functionality wrt logging(setting, getting log level).
> 
> Is this what we are removing support for? https://github.com/rudderlabs/rudder-cli/blob/e6fb53b728a253a44fafcbacafd2e0ebaa28b2ac/main.go#L69

Yes

Also there are some warehouse related functionalities(trigger-upload and a few other). If the cli isn't used for it, we could entirely remove it. @lvrach

**Comment by Sidddddarth** [comment]
In conclusion, kept the below functionalities intact:
1. Admin.ServerConfig
2. Admin.GetFormattedEnv
3. Admin.SetLogLevel
4. Admin.GetLoggingConfig
5. Warehouse.TriggerUpload
6. Warehouse.Query
7. Warehouse.ConfigurationTest

We can remove more of these if they're unused or out of favour.

[rudder-cli PR](https://github.com/rudderlabs/rudder-cli/pull/248)

**Comment by atzoum** [comment]
Anyone who is using rudder-cli to comment here?

**Review by atzoum — APPROVED** [review]

**Pull request merged**
