### PR TITLE
fix(core): order inserts(updates) to avoid deadlocks

### PR DESCRIPTION
**Pull request by Sidddddarth**
# Description

rSources handlers from different modules can cause deadlock when attempting unordered inserts between two competing transactions. statsCollector now sorts the inserts beforehand to avoid deadlock.

``` Process 32628 waits for ShareLock on transaction 811911309; blocked by process 12444.
	Process 12444 waits for ShareLock on transaction 811911471; blocked by process 32628.
	Process 32628: insert into "rsources_stats" (
			job_run_id,
			task_run_id,
			source_id,
			destination_id,
			in_count,
			out_count,
			failed_count
		) values ($1, $2, $3, $4, $5, $6, $7)
		on conflict(db_name, job_run_id, task_run_id, source_id, destination_id)
		do update set
		in_count = "rsources_stats".in_count + excluded.in_count,
		out_count = "rsources_stats".out_count + excluded.out_count,
		failed_count = "rsources_stats".failed_count + excluded.failed_count,
		ts = NOW()
	Process 12444: insert into "rsources_stats" (
			job_run_id,
			task_run_id,
			source_id,
			destination_id,
			in_count,
			out_count,
			failed_count
		) values ($1, $2, $3, $4, $5, $6, $7)
		on conflict(db_name, job_run_id, task_run_id, source_id, destination_id)
		do update set
		in_count = "rsources_stats".in_count + excluded.in_count,
		out_count = "rsources_stats".out_count + excluded.out_count,
		failed_count = "rsources_stats".failed_count + excluded.failed_count,
		ts = NOW()
2022-07-14 07:08:08.652 GMT [32628] HINT:  See server log for query details.
2022-07-14 07:08:08.652 GMT [32628] CONTEXT:  while inserting index tuple (107,12) in relation "rsources_stats"
2022-07-14 07:08:08.652 GMT [32628] STATEMENT:  insert into "rsources_stats" (
			job_run_id,
			task_run_id,
			source_id,
			destination_id,
			in_count,
			out_count,
			failed_count
		) values ($1, $2, $3, $4, $5, $6, $7)
		on conflict(db_name, job_run_id, task_run_id, source_id, destination_id)
		do update set
		in_count = "rsources_stats".in_count + excluded.in_count,
		out_count = "rsources_stats".out_count + excluded.out_count,
		failed_count = "rsources_stats".failed_count + excluded.failed_count,
		ts = NOW()
```

## Notion Ticket

[pq: deadlock detected](https://www.notion.so/rudderstacks/aab9175babbb48918aa17fb3f91b9988?v=330acd9e9d1d4ff989288186ca778fca&p=29d73765c4c4454c94d9b76fac1b1463)

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Review by atzoum — APPROVED** [review]
LGTM

**Comment by atzoum** [comment]
we need this to be included in 0.2.1
therefore this should target the hotfix branch instead of master

**Review by cisse21 — APPROVED** [review]

**Review by lvrach — COMMENTED** [review]
Can we add concurrent tests to ensure the deadlock issue is resolved ?

**Comment by cisse21** [comment]
@lvrach Let's add all tests once we are sure that there are no crashes on hosted post release

**Pull request merged**
